//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamEase.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamEase.Resources.HomePageResource", typeof(HomePageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   An Account benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AnAccount {
            get {
                return ResourceManager.GetString("AnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .NET Web Application benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ASPNETMVCWebApplication {
            get {
                return ResourceManager.GetString("ASPNETMVCWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Benefits benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Benefits {
            get {
                return ResourceManager.GetString("Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bootstrap HTML Website Templates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BootstrapHTMLWebsiteTemplates {
            get {
                return ResourceManager.GetString("BootstrapHTMLWebsiteTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detailed Documentation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DetailedDocumentation {
            get {
                return ResourceManager.GetString("DetailedDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email Address benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Envato Portfolio benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EnvatoPortfolio {
            get {
                return ResourceManager.GetString("EnvatoPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAQ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes, it&apos;s in our plan, but for now, we couldn&apos;t guarantee the release time. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQFourAnswer {
            get {
                return ResourceManager.GetString("FAQFourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can you create a .NET Core MVC version? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQFourQuestion {
            get {
                return ResourceManager.GetString("FAQFourQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We only provide support for fixing existing bugs in the templates and answering questions regarding the existing features. Step-by-step guidance on how to do your custom modifications, how to solve bugs after your own modifications and direct installation are not part of our support. Thank you so much for your understanding. We will spend our time to create more amazing templates for you. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQOneAnswer {
            get {
                return ResourceManager.GetString("FAQOneAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How is the support policy? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQOneQuestion {
            get {
                return ResourceManager.GetString("FAQOneQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes, you can. Go to &quot;/Views/Shared/_FooterBeforeLogin.cshtml&quot; and find the footer section to edit or remove the copyright text. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQThreeAnswer {
            get {
                return ResourceManager.GetString("FAQThreeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can I edit or remove the Copyright text at the footer? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQThreeQuestion {
            get {
                return ResourceManager.GetString("FAQThreeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Answer is: Immediately after purchase. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQTwoAnswerPartOne {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   for more information, there is “Downloading your items” section at the end of this article. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQTwoAnswerPartTwo {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When can I download the file after purchase the item? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAQTwoQuestion {
            get {
                return ResourceManager.GetString("FAQTwoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User management benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic regrading benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature10 {
            get {
                return ResourceManager.GetString("Feature10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If a teacher selects the wrong answer as the correct one and discovers this after the students have taken the exam, their results will be re-graded automatically if they want to change the answer. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature10Description {
            get {
                return ResourceManager.GetString("Feature10Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyze Chart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature11 {
            get {
                return ResourceManager.GetString("Feature11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charts to analyze results, questions that most students answered incorrectly, and more. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature11Description {
            get {
                return ResourceManager.GetString("Feature11Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strict rules benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature12 {
            get {
                return ResourceManager.GetString("Feature12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot skip questions. Cannot copy the question text while taking the exam. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature12Description {
            get {
                return ResourceManager.GetString("Feature12Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System admin can create, update and delete users. Students and teachers can register an account by themselves too. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature1Description {
            get {
                return ResourceManager.GetString("Feature1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store question bank benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save your question bank and re-use it in different exams with different mark distributions. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature2Description {
            get {
                return ResourceManager.GetString("Feature2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schedule exam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can save an exam now and schedule it to start later. Then, publish an exam when it is ready to be announced to the students. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature3Description {
            get {
                return ResourceManager.GetString("Feature3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Students&apos; result benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Students&apos; results can be exported to Excel or PDF. You can also sort the result list by student score to see the top students in the exam. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature4Description {
            get {
                return ResourceManager.GetString("Feature4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import questions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature5 {
            get {
                return ResourceManager.GetString("Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can create questions in batches by importing them from Excel. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature5Description {
            get {
                return ResourceManager.GetString("Feature5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import users benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature6 {
            get {
                return ResourceManager.GetString("Feature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can create user accounts in batches by importing them from Excel. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature6Description {
            get {
                return ResourceManager.GetString("Feature6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Randomize question benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature7 {
            get {
                return ResourceManager.GetString("Feature7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can choose to randomise or un-randomize the question order of an exam. Randomizing questions can prevent cheating because students cannot discuss the answers as they are getting different questions at one time. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature7Description {
            get {
                return ResourceManager.GetString("Feature7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release answer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature8 {
            get {
                return ResourceManager.GetString("Feature8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can choose to release or unrelease the answers to the questions. Before the answers are released, students will get their results but will not be able to see the correct answers. We recommend releasing the answer only after all the students have taken the exam. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature8Description {
            get {
                return ResourceManager.GetString("Feature8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export result benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature9 {
            get {
                return ResourceManager.GetString("Feature9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Students&apos; result can be exported to excel or pdf. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Feature9Description {
            get {
                return ResourceManager.GetString("Feature9Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Features benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Features benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Features1 {
            get {
                return ResourceManager.GetString("Features1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExamEase Contains Full Essential Features To Conduct An Exam. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FeaturesDescription {
            get {
                return ResourceManager.GetString("FeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill your details to register. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Fillyourdetailstoregister {
            get {
                return ResourceManager.GetString("Fillyourdetailstoregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill your username and password to sign in. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Fillyourusernameandpasswordtosignin {
            get {
                return ResourceManager.GetString("Fillyourusernameandpasswordtosignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follow Us benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follow our social media to get updates or news about the projects. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FollowUsDescription {
            get {
                return ResourceManager.GetString("FollowUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forgot your password? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frequently Asked Questions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Sayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExamEase is an online exam system that delivers exam management, question bank management, automated grading, an analytical dashboard, and more. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kur&apos;anı Kerimi anlayarak okumak artık okadar zor değil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomeTitleOne {
            get {
                return ResourceManager.GetString("HomeTitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomeTitleTwo {
            get {
                return ResourceManager.GetString("HomeTitleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import &amp; Export benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ImportAndExport {
            get {
                return ResourceManager.GetString("ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExamEase FAQ Articles benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NetStarterFAQArticles {
            get {
                return ResourceManager.GetString("NetStarterFAQArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Our Products benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register &amp; Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RegisterAndLogin {
            get {
                return ResourceManager.GetString("RegisterAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember me? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role Permission benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Up benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifications benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   the following article benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TheFollowingArticle {
            get {
                return ResourceManager.GetString("TheFollowingArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To ExamEase benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToNetStarter {
            get {
                return ResourceManager.GetString("ToNetStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload File benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Useful Links benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View More benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExamEase benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WebAppTitle {
            get {
                return ResourceManager.GetString("WebAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After Purchasing, You Will Get A Zip File Which Contains The Following benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhatyougetDescription {
            get {
                return ResourceManager.GetString("WhatyougetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save your question bank and re-use it in different exams with different mark distributions. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhyUs1Description {
            get {
                return ResourceManager.GetString("WhyUs1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reusable Questions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhyUs1Title {
            get {
                return ResourceManager.GetString("WhyUs1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Say goodbye to the hassle of paper-based exams and the time-consuming manual grading system. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhyUs2Description {
            get {
                return ResourceManager.GetString("WhyUs2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Your Time benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhyUs2Title {
            get {
                return ResourceManager.GetString("WhyUs2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Streamline your examination process. Create exam, select questions from question bank, allocate marks, done! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhyUs3Description {
            get {
                return ResourceManager.GetString("WhyUs3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple Process benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhyUs3Title {
            get {
                return ResourceManager.GetString("WhyUs3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Randomizing Question Order, Scheduling Exam Start Date &amp; Time, Storing Your Question Bank, And More. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhyUsDescription {
            get {
                return ResourceManager.GetString("WhyUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Why ExamEase benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WhyUsTitle {
            get {
                return ResourceManager.GetString("WhyUsTitle", resourceCulture);
            }
        }
    }
}
